# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r:
  - 3.0
  - 3.1
  - 3.2
  - 3.3
  - 3.4
  - 3.5
  - oldrel
  - release
  - devel
sudo: false
cache: packages
after_success:
  - Rscript -e 'covr::codecov()'
